### ISSUE TITLE
Fall back to authentication via ENV

### ISSUE THREAD

**Issue by garethr** [dogsheep/github-to-sqlite#33]
Would you accept a PR that falls back to looking for an environment variable for the GitHub token? Specifically a change here:
https://github.com/dogsheep/github-to-sqlite/blob/c34d5a18bfc41fa08755ba3d5cf9fe09ff204238/github_to_sqlite/cli.py#L271

I'd like to use `github-to-sqlite` in a GitHub Action workflow and this would be simpler than trying to fill out the prompt or generate a file with sensitive content.

Wanted to check first, I'm happy to submit a PR with tests and updates to the docs.

**Comment by simonw** [comment]
Sure, that sounds fine to me.

**Comment by simonw** [comment]
The `auth.json` mechanism this uses is standard across all of the other dogsheep tools - it's actually designed so you can have one `auth.json` with a bunch of different credentials for different tools:

```json
{
    "goodreads_personal_token": "...",
    "goodreads_user_id": "...",
    "github_personal_token": "...",
    "pocket_consumer_key": "...",
    "pocket_username": "...",
    "pocket_access_token": "..."
}
```
But... `github-to-sqlite` does feel like it deserves a special case here, since it's such a good fit for running inside of GitHub Actions. So I don't think it will harm the family of tools too much if this has an environment variable alternative to the `-a` file.

**Comment by garethr** [comment]
I also go it working with:

```yaml
run: echo ${{ secrets.github_token }} | github-to-sqlite auth
```

**Comment by simonw** [comment]
Documented here: https://github.com/dogsheep/github-to-sqlite/blob/10fb34de41aaa35681f08b5991540d65bfcf2e2e/README.md#authentication
